### ISSUE TITLE
construct the negative samples 

### ISSUE THREAD

**Issue by CH00101** [xinghd142857/PU-EPP#2]
Thank you for doing such a great job. I would like to ask how you construct the negative samples mentioned in your literature. Is there any specific implementation code? I saw that you calculated the weights for different enzymes after sampling, how the weights are determined for the number, I did not find the corresponding code. Another thing is that I saw in your literature that you use PU learning to exclude potential positive samples. When I reproduced your work, I found that there was no potential positive sample output. I hope you can answer it. Thank you.

**Comment by xinghd142857** [comment]
Since I have left the institute, I no longer have access to the original code. However, the implementation of negative sampling is straightforward and follows the formula directly. The weight of the “negative” enzyme–substrate pairs was calculated as: `weight = -np.log10((10 / (X_max - X_min)) * ((X - X_min) / (X_max - X_min)))`  X_max : The maximum number of corresponding substrates of an enzyme, X_min: The minimum number of corresponding substrates of an enzyme.

Regarding the calculation of attention weights, you can refer to the code in /utils/attentionvis.py.

As for the exclusion of potential positive samples, this is done during the model training phase. I’m not sure what you mean by “there was no potential positive sample output.” The training set provided is only an example. During training, potential positive samples below a specific threshold are simply removed.

Thank you for your interest in our model.

**Comment by xinghd142857** [comment]
> Since I have left the institute, I no longer have access to the original code. However, the implementation of negative sampling is straightforward and follows the formula directly. The weight of the “negative” enzyme–substrate pairs was calculated as: `weight = -np.log10((10 / (X_max - X_min)) * ((X - X_min) / (X_max - X_min)))` X_max : The maximum number of corresponding substrates of an enzyme, X_min: The minimum number of corresponding substrates of an enzyme.
> 
> Regarding the calculation of attention weights, you can refer to the code in /utils/attentionvis.py.
> 
> As for the exclusion of potential positive samples, this is done during the model training phase. I’m not sure what you mean by “there was no potential positive sample output.” The training set provided is only an example. During training, potential positive samples below a specific threshold are simply removed.
> 
> Thank you for your interest in our model.

Since I have left the institute, I no longer have access to the original code. However, the implementation of negative sampling is straightforward and follows the formula directly. The weight of the “negative” enzyme–substrate pairs was calculated as: `weight = -np.log10((10 / (X_max - X_min)) * ((X - X_min) / (X_max - X_min)))` X_max : The maximum number of corresponding substrates of an enzyme, X_min: The minimum number of corresponding substrates of an enzyme.

Regarding the calculation of attention weights, you can refer to the code in /utils/attentionvis.py.

As for the exclusion of potential positive samples, this is done during the model training phase. I’m not sure what you mean by “there was no potential positive sample output.” The training set provided is only an example. During training, potential positive samples with a specific threshold are simply removed.

Thank you for your interest in our model.

**Comment by CH00101** [comment]
Sorry, I didn't express myself clearly. I have seen the formula for calculating the weight of negative samples in the article, and I also calculated the weight based on this formula. But I found some problems. For example, when X=Xmin, the formula is log0 which is meaningless. How did you solve this? Another one is, for example, after the weight is obtained, how to determine the number of negative samples for this enzyme? If the weight is 2.1 or 2.7, then how many negative samples should be constructed for this enzyme. Also, as I said, when I was training your model, I changed the epoch to 20 due to time constraints. After the training was completed, I found no potential positive samples deleted in PU-EPP/data/U_m_P. Looking forward to your reply, thank you

**Comment by xinghd142857** [comment]
> Sorry, I didn't express myself clearly. I have seen the formula for calculating the weight of negative samples in the article, and I also calculated the weight based on this formula. But I found some problems. For example, when X=Xmin, the formula is log0 which is meaningless. How did you solve this? Another one is, for example, after the weight is obtained, how to determine the number of negative samples for this enzyme? If the weight is 2.1 or 2.7, then how many negative samples should be constructed for this enzyme. Also, as I said, when I was training your model, I changed the epoch to 20 due to time constraints. After the training was completed, I found no potential positive samples deleted in PU-EPP/data/U_m_P. Looking forward to your reply, thank you

In this work, Xmin = 1, indicating the enzyme only applies to one substrate. For your example, if the weight is 2.7 and the enzyme E has 5 positive sample substrates, approximately 5 * 2.7 ≈ 14 negative examples (unlabeled samples) will be generated for enzyme E.

Regarding the training process, you can inspect the model’s output. During the PU-learning stage, the model will only remove a sample if its output exceeds 0.9. Your issue might stem from the number of epoch or the quality of the training dataset.
